src/support/models.py
from src import db
from src.misc.constants import TICKET_TYPES, CHAT_TYPES, TICKET_STATUS


class Message(db.EmbeddedDocument):
    sender = db.StringField()
    text = db.StringField()
    media = db.StringField()
    media_type = db.StringField(choices=CHAT_TYPES)
    date = db.DateTimeField()

    def __repr__(self):
        return 'Message \n Sender: {}, Text: {}'.format(self.sender, self.text)

class Ticket(db.Document):
    type = db.StringField(choices=TICKET_TYPES)
    date = db.DateTimeField()
    title = db.StringField()
    sender = db.StringField()
    messages = db.ListField(db.EmbeddedDocumentField(Message))
    associated_admin = db.StringField()
    related_product = db.StringField()
    status = db.StringField(default=TICKET_STATUS['PENDING_ADMIN_ANSWER'], choices=TICKET_STATUS)
    meta = {'indexes': ['sender']}


    @classmethod
    def get(cls, id):
        return cls.objects.get(pk=id)

src/support/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SelectField, TextAreaField
from flask_wtf.file import FileField, FileRequired
from wtforms.validators import InputRequired, Length
from src.misc.constants import TICKET_TYPES


class TicketForm(FlaskForm):
    ticket_type = SelectField('Ticket Type', id='ticket_type', choices=list(TICKET_TYPES.items()), validators=[InputRequired()])
    # related_product = SelectField(choices=??)
    title = StringField('Title', id='title', validators=[InputRequired(), Length(min=3, max=1024)])
    message_text = TextAreaField('Message', id='message_text', validators=[InputRequired(), Length(min=5, max=2048)])
    message_media = FileField('Attachment', id='message_media')

class AnswerForm(FlaskForm):
    message_text = TextAreaField('Message', id='message_text', validators=[InputRequired(), Length(min=5, max=2048)])
    message_media = FileField('Attachment', id='message_media')

src/support/__init__.py
from flask import Blueprint

support_blueprint = Blueprint('support', __name__, template_folder='templates')

from . import views
from . import sockets

src/support/views.py
from flask import render_template, flash, redirect, url_for, abort
from flask_login import login_required, current_user
from src.support import support_blueprint
from src.misc.requires_roles import requires_roles
from src.misc.exceptions import NotFound
from src.misc.constants import TICKET_STATUS
from .forms import TicketForm, AnswerForm
from .models import Ticket, Message
from datetime import datetime
import os
from src import app
from src.misc.helpers import get_type_from_extension, get_iran_datetime
from mongoengine import errors as MongoEngineExceptions
from uuid import uuid4


@support_blueprint.route('/ticket/add/', methods=['GET', 'POST'])
@login_required
def add_ticket():
    form = TicketForm()
    if form.validate_on_submit():
        filename = None
        if form.message_media.data is not None:
            ext = os.path.splitext(form.message_media.data.filename)[1]
            try:
                media_type = get_type_from_extension(ext)
            except TypeError:
                flash('File Extension %s is not allowed.' % ext)
                return redirect(url_for('support.add_ticket'))
            filename = current_user.username + '_' + str(datetime.utcnow().strftime('%Y-%m-%d_%H-%M-%S')) + '_' + uuid4().hex + ext
            form.message_media.data.save(os.path.join(
                app.config['UPLOAD_FOLDER'], 'ticket_media', filename
            ))

            ticket = Ticket(type=form.ticket_type.data, date=datetime.utcnow(), title=form.title.data,
                            messages=[Message(sender=current_user.username, text=form.message_text.data,
                                              media=filename, media_type=media_type,
                                              date=datetime.utcnow())],
                                              sender=current_user.username, related_product='NONE')
        else:
            ticket = Ticket(type=form.ticket_type.data, date=datetime.utcnow(), title=form.title.data,
                            messages=[Message(sender=current_user.username, text=form.message_text.data,
                                              media=filename, date=datetime.utcnow())],
                                              sender=current_user.username, related_product='NONE')
        try:
            ticket.save()
            flash('Saved Successfully')
            return redirect(url_for('support.view_ticket', id=ticket.id))
        except MongoEngineExceptions.ValidationError:
            flash('You data is not valid.')
            return redirect(url_for('support.add_ticket'))

    return render_template('add_ticket.html', form=form)


@support_blueprint.route('/ticket/view/<string:id>/', methods=['GET', 'POST'])
@login_required
def view_ticket(id):
    form = AnswerForm()
    try:
        ticket = Ticket.get(id)
        if ticket.sender != current_user.username and current_user.role != 'ADMIN':
            raise NotFound
    except MongoEngineExceptions.DoesNotExist:
        return abort(404)
    except NotFound:
        return abort(404)
    except Exception as error:
        print(error)
        flash('Database error.')
        return abort(500)

    if form.validate_on_submit():
        filename = None
        message = None
        if form.message_media.data is not None:
            ext = os.path.splitext(form.message_media.data.filename)[1]
            try:
                media_type = get_type_from_extension(ext)
            except TypeError:
                flash('File Extension %s is not allowed.' % ext)
                return redirect(url_for('support.add_ticket'))
            filename = current_user.username + '_' + str(
                datetime.utcnow().strftime('%Y-%m-%d_%H-%M-%S')) + '_' + uuid4().hex + ext
            form.message_media.data.save(os.path.join(
                app.config['UPLOAD_FOLDER'], 'ticket_media', filename
            ))
            message = Message(sender=current_user.username, text=form.message_text.data,
                              media=filename, media_type=media_type, date=datetime.utcnow())
        else:
            message = Message(sender=current_user.username, text=form.message_text.data, date=datetime.utcnow())

        try:
            ticket.messages.append(message)
            if current_user.role == 'ADMIN' and current_user == ticket.sender:
                ticket.status = TICKET_STATUS['PENDING_ADMIN_ANSWER']
            else:
                ticket.status = TICKET_STATUS['PENDING_USER_ANSWER']
            ticket.save()
        except MongoEngineExceptions.ValidationError as error:
            print(error)
            flash('message cant be validated.')
            return redirect(url_for('support.view_ticket', id=ticket.id))
        except Exception as error:
            print(error)
            flash('Database error.')
            abort(500)

    return render_template('view_ticket.html', form=form, ticket=ticket, datetime=get_iran_datetime(ticket.date), id=id)


@support_blueprint.route('/ticket/list/')
@support_blueprint.route('/ticket/list/<string:username>/')
@login_required
def list_tickets(username = None):
    if username == None:
        tickets = Ticket.objects(sender=current_user.username)
        return render_template('list_tickets.html', tickets=tickets, get_iran_datetime=get_iran_datetime)

    if current_user.username == username or current_user.role == 'ADMIN':
        tickets = Ticket.objects(sender=username)
        return render_template('list_tickets.html', tickets=tickets, get_iran_datetime=get_iran_datetime)
    else:
        abort(404)


@support_blueprint.route('/ticket/close/<string:id>/')
@login_required
def close_ticket(id):
    try:
        ticket = Ticket.get(id)
        if ticket.sender != current_user.username and current_user.role != 'ADMIN':
            raise NotFound
        ticket.status = TICKET_STATUS['CLOSED']
        ticket.save()
        flash('ticket closed successfully.')
        return redirect(url_for('support.view_ticket', id=ticket.id))
    except MongoEngineExceptions.DoesNotExist:
        abort(404)
    except NotFound:
        abort(404)
    except Exception as error:
        print(error)
        flash('Database error in closing ticket.')
        return redirect(url_for('support.view_ticket', id=id))


@support_blueprint.route('/ticket/list_unanswered/')
@login_required
@requires_roles('ADMIN')
def list_unanswered_tickets():
    try:
        tickets = Ticket.objects(status=TICKET_STATUS['PENDING_ADMIN_ANSWER'])
    except MongoEngineExceptions.DoesNotExist:
        abort(404)
    except Exception as error:
        print(error)
        flash('Database error in getting unanswered tickets.')
        return redirect(url_for('admin.admin'))
    return render_template('list_unanswered_tickets.html', tickets=tickets, get_iran_datetime=get_iran_datetime)

src/support/templates/add_ticket.html
{% extends 'base.html' %}
{% block content %}
    <h1>Add Ticket</h1>
<form action="{{ url_for('support.add_ticket') }}" method="POST" enctype="multipart/form-data"  name="add-ticket">
    {{ form.hidden_tag() }}
    <p>
        Ticket Form:
    </p>
    {{ show_input('ticket_type') }}
    {{ show_input('title') }}
    {{ show_input('message_text') }}
    {{ show_input('message_media') }}
    <input type="submit" value="Send">
</form>
{% endblock %}

src/support/templates/list_tickets.html
{% extends 'base.html' %}
{% block content %}
    <h1>All Tickets</h1>
    {% for ticket in tickets %}
        <p>
            Title {{ ticket.title }} <br>
            Related Section: {{ ticket.type }} <br>
            Date Created: {{ get_iran_datetime(ticket.date) }} <br>
            Related Product: {{ ticket.related_product }} <br>
            <a href="{{ url_for('support.view_ticket', id=ticket.id) }}">View</a>
        </p>
        <hr>
    {% endfor %}
{% endblock %}

src/support/templates/list_unanswered_tickets.html
{% extends 'base.html' %}
{% block content %}
    <h1>Unanswered Tickets</h1>
    {% for ticket in tickets %}
        <p>
            Title {{ ticket.title }} <br>
            Related Section: {{ ticket.type }} <br>
            Date Created: {{ datetime }} <br>
            Related Product: {{ ticket.related_product }} <br>
            <a href="{{ url_for('support.view_ticket', id=ticket.id) }}">View</a>
        </p>
        <hr>
    {% endfor %}
{% endblock %}

src/support/templates/view_ticket.html
{% extends 'base.html' %}
{% block content %}
    <h1>View Ticket</h1>
    <form action="{{ url_for('support.view_ticket', id=id) }}" method="POST" enctype="multipart/form-data"
          name="view-ticket">
        {{ form.hidden_tag() }}
        <p>
            Title {{ ticket.title }} <br>
            Related Section: {{ ticket.type }} <br>
            Date Created: {{ datetime }} <br>
            Related Product: {{ ticket.related_product }} <br>
        </p>
        {% for message in ticket.messages %}
            <p>
                Sender: {{ message.sender }} <br>
                Text: {{ message.text }} <br>
                {% if message.media %}
                    Media:
                    {% if message.media_type == 'IMAGE' %}
                        <img width="320" height="240"
                             src="{{ url_for('static', filename='/'.join(['user_data', 'ticket_media', message.media])) }}"
                             alt="">
                    {% elif message.media_type == 'VIDEO' %}
                        <video width="320" height="240" controls>
                            <source src="{{ url_for('static', filename='/'.join(['user_data', 'ticket_media', message.media])) }}"
                                    type="video/{{ message.media.split('.')[1] }}">
                            Your browser does not support the video tag.
                        </video>
                    {% endif %}
                {% endif %}
            </p>
            <hr>
        {% endfor %}
        {% if ticket.status != 'CLOSED' or current_user.role == 'ADMIN' %}
            <h3>Answer to message:</h3>
            {{ show_input('message_text') }}
            {{ show_input('message_media') }}
            <input type="submit" value="Send">
        {% else %}
            Ticket is closed. you cant post answer.
        {% endif %}
        <a href="http://localhost:8080{{ url_for('support.close_ticket', id=ticket.id) }}">Close</a>
    </form>
{% endblock %}